from enum import Enum

class MetroType(Enum):
    HEZI_ASLANOV = 1
    EHMADLI = 2
    XALQLAR_DOSTLUGU = 3
    NEFTCILER = 4
    QARA_QARAYEV = 5
    KOROGLU = 6
    ULDUZ = 7
    NERIMAN_NERIMANOV = 8
    GENCLIK = 9
    MAY_28 = 10
    NIZAMI = 11
    ELMLER_AKADEMIYASI = 12
    INSAATCHILAR = 13
    YANVAR_20 = 14
    MEMAR_ECEMI = 15
    NESIMI = 16
    AZADLIQ_PROSPEKTI = 17
    CEFER_CABBARLI = 18
    XETAI = 19
    SAHIL = 20
    ICHERI_SHEHER = 21
    BAKMIL = 22
    DERNEGUL = 23
    AVTOVAGZAL = 24
    NOV_8 = 25
    XOJASEN = 26
